version: '3.8'


services:
  ShippingService:
    image: soekopaacykel/shipping-service:latest
    environment:
      - Deliverys=/forsendelser
    ports:
      - "5001:8080"
    networks:
      - default
    volumes:
      - haav-vol:/forsendelser


  DeliveryService:
    image: soekopaacykel/delivery-service:latest
    environment:
      - Deliverys=/forsendelser
    ports:
      - "5002:8080"
    networks:
      - default
    volumes:
      - haav-vol:/forsendelser

volumes:
  haav-vol:
    external: false

networks:
  default:
    driver: bridge
    name: mitnet
